
- id: wallpapers1
  desc: 'Cute animations to use as wallpapers'
  code:
  - bootstrapping_olympics.batch_jobs1
  - robots: ["rsim-d_SE2_rb_v-cam180-stereo-wp1",
             "rsim-d_SE2_car_v-cam360-wp1",
             "rsim-d_SE2_car_v-rf360-wp1"
             #"rsim-d_SE2_rb_v-fs_rand144-wp1"
             ]
    agents: [random_agent]
    explore:
        max_episode_len: 12
        explorer: fixed_1ss
        num_episodes: 1
        num_episodes_videos: 1
        videos: [wallpaper]



- id: wallpapers2
  desc: 'Cute animations to use as wallpapers'
  code:
  - bootstrapping_olympics.batch_jobs1
  - robots: ["rsim-v_brai_blind-wp2"]
    agents: [random_agent]
    explore:
        max_episode_len: 15
        explorer: fixed_s1
        num_episodes: 1
        num_episodes_videos: 1
        videos: [wallpaper]


- id: wallpapers3
  desc: 'Cute animations to use as wallpapers'
  code:
  - bootstrapping_olympics.batch_jobs1
  - robots: ["rsim-v_brai_blind-wp3"]
    agents: [random_agent] 
    explore:
        max_episode_len: 15
        explorer: fixed_m1
        num_episodes: 1
        num_episodes_videos: 1
        videos: [wallpaper]


