
- id: d_SE2_car_v_w-cam360-wp1
  desc: ""
  code:
   - vehicles_boot.BOVehicleSimulation
   - dt: 0.05
     id_vehicle: d_SE2_car_v_w-cam360
     id_world: wp1


- id: d_SE2_car_v-rf360-wp1
  desc: ""
  code:
    - vehicles_boot.BOVehicleSimulation
    - dt: 0.05
      id_vehicle: d_SE2_car_v-rf360
      id_world: wp1


- id: d_SE2_rb_v-fs_rand144-wp1
  desc: ""
  code:
   - vehicles_boot.BOVehicleSimulation
   - dt: 0.05
     id_vehicle: d_SE2_rb_v-fs_rand144
     id_world: wp1

      


- id: d_SE2_rb_v-cam180-stereo-wp1
  desc: ""
  code:
   - vehicles_boot.BOVehicleSimulation
   - dt: 0.05
     id_vehicle: d_SE2_rb_v-cam180-stereo
     id_world: wp1
