- id: EstStats
  desc: Estimates some observations statistics.
  code:
      - boot_agents.EstStats
      - beta: 1


- id: BDSAgent_C1
  desc: "BDS agent"
  code:
      - boot_agents.BDSAgent
      - beta: 1
        change_fraction: 0.5
