
- id: r_fs_A
  desc: ""
  code:
     - vehicles_boot.BOVehicleSimulation
     - dt: 0.1
       id_vehicle: v_fs_A
       id_world: SBox2_10a

- id: r_cam_A
  desc: ""
  code:
     - vehicles_boot.BOVehicleSimulation
     - dt: 0.1
       id_vehicle: v_cam_A
       id_world: SBox3_10scale05

- id: r_fs_B
  desc: "Field sampler with square disposition"
  code:
     - vehicles_boot.BOVehicleSimulation
     - dt: 0.1
       id_vehicle: v_fs_B
       id_world: SBox2_10a

- id: r_cam_A_n1
  desc: "Camera with permutation perturbation."
  code:
     - bootstrapping_olympics.examples.EquivRobot
     - robot: r_cam_A
       obs_nuisance: n_rpermA
       cmd_nuisance: []

- id: r_cam_A_n2
  desc: "Camera with scaling perturbation."
  code:
     - bootstrapping_olympics.examples.EquivRobot
     - robot: r_cam_A
       obs_nuisance: n_rscaleA
       cmd_nuisance: []

- id: r_rf_A
  desc: ""
  code:
     - vehicles_boot.BOVehicleSimulation
     - dt: 0.1
       id_vehicle: v_rf_A
       id_world: stochastic_box_10

- id: r_rf_A_n1
  desc: "Range-finder with scaling perturbation."
  code:
     - bootstrapping_olympics.examples.EquivRobot
     - robot: r_rf_A
       obs_nuisance: n_rscaleA
       cmd_nuisance: []

- id: r_rf_A_n2
  desc: "Range-finder with permutation perturbation."
  code:
     - bootstrapping_olympics.examples.EquivRobot
     - robot: r_rf_A
       obs_nuisance: n_rpermA
       cmd_nuisance: []

