- id: bo_app1a
  desc: 'Simple example without nuisances.'
  code:
  - bootstrapping_olympics.batch_jobs1
  - robots: [r_cam_A, r_rf_A, r_fs_A]
    agents: [BDSAgent_C1, BDSAgent_C2] #, BDSAgent_C3]
    explore:
        num_episodes: 200
        num_episodes_videos: 5
        explorer: expswitch_t1
        max_episode_len: 30

    servo:
        num_episodes: 20
        num_episodes_videos: 5
        max_episode_len: 60
        displacement: 1
        
    servonav:
        num_episodes: 20
        num_episodes_videos: 20
        max_episode_len: 600
        resolution: 0.25
        fail_if_not_working: false

- id: bo_app1b
  desc: "This is to show the effect of simple nuisances."
  code:
  - bootstrapping_olympics.batch_jobs1
  - robots: [r_cam_A, r_rf_A, r_fs_A, 
             r_fs_B, r_fs_C, r_fs_D, r_rf_A_n1, 
             r_rf_A_n2, r_cam_A_n1, r_cam_A_n2]
    agents: [BDSAgent_C1, BDSAgent_C2, EstStats]

    explore:
        num_episodes: 200
        num_episodes_videos: 5
        explorer: expswitch_t1
        max_episode_len: 30

    servo:
        num_episodes: 20
        num_episodes_videos: 5
        max_episode_len: 40
        displacement: 1
        
    servonav:
        num_episodes: 20
        num_episodes_videos: 5
        max_episode_len: 10000 # no limitations
        resolution: 0.25
        fail_if_not_working: false
        
- id: bo_app1_stats
  desc: "Embedding for different nuisances."
  code:
  - bootstrapping_olympics.batch_jobs1
  - robots: [r_cam_A,  r_cam_A_n1, r_cam_A_n2,
             r_rf_A, r_rf_A_n1, r_rf_A_n2,
             r_fs_A, r_fs_B, r_fs_C, r_fs_D]
    agents: [embed, EstStats]

    explore:
        num_episodes: 100
        num_episodes_videos: 0
        explorer: expswitch_t1
        max_episode_len: 10

# TODO: Add one with cars
# TODO: Add one with cars


- id: bo_app1c
  desc: 'Differential drive.'
  code:
  - bootstrapping_olympics.batch_jobs1
  - robots: ["rsim-d_SE2_dd_v-cam360", 
             "rsim-d_SE2_dd_v-rf360", 
             "rsim-d_SE2_dd_v-fs_05_rand144", 
             "rsim-d_SE2_dd_v-fs_05_12x12", 
             ]
    agents: [BDSAgent_C1, BDSAgent_C2] #, BDSAgent_C3]
    explore:
        num_episodes: 200
        num_episodes_videos: 5
        explorer: expswitch_t1
        max_episode_len: 30

    servo:
        num_episodes: 20
        num_episodes_videos: 5
        max_episode_len: 60
        displacement: 1
        
    servonav:
        num_episodes: 20
        num_episodes_videos: 20
        max_episode_len: 600
        resolution: 0.25
        fail_if_not_working: false

- id: bo_app1d
  desc: 'Experiments with car-like.'
  code:
  - bootstrapping_olympics.batch_jobs1
  - robots: ["rsim-d_SE2_car_v-cam360", 
             "rsim-d_SE2_car_v-rf360", 
             "rsim-d_SE2_car_v-fs_05_rand144", 
             "rsim-d_SE2_car_v-fs_05_12x12", 
             ]
    agents: [BDSAgent_C1, BDSAgent_C2] #, BDSAgent_C3]
    explore:
        num_episodes: 200
        num_episodes_videos: 5
        explorer: expswitch_t1
        max_episode_len: 30

    servo:
        num_episodes: 20
        num_episodes_videos: 5
        max_episode_len: 60
        displacement: 1
        
    servonav:
        num_episodes: 20
        num_episodes_videos: 20
        max_episode_len: 600
        resolution: 0.25
        fail_if_not_working: false
