- id: bo_app1a
  desc: 'Simple example without nuisances.'
  code:
  - bootstrapping_olympics.batch_jobs1
  - robots: [r_cam_A, r_rf_A, r_fs_A]
    agents: [embed, BDSAgent_C1, EstStats]
    explore:
        num_episodes: 200
        num_episodes_videos: 5
        explorer: expswitch_t1
        max_episode_len: 30
    servo:
        num_episodes: 20
        num_episodes_videos: 20
        max_episode_len: 10
        displacement: 2
    servonav:
        num_episodes: 20
        num_episodes_videos: 20
        max_episode_len: 600
        resolution: 0.25
        fail_if_not_working: false

- id: bo_app1b
  desc: "This is to show the effect of simple nuisances."
  code:
  - bootstrapping_olympics.batch_jobs1
  - robots: [r_cam_A, r_rf_A, r_fs_A, 
             r_fs_B, r_fs_C, r_fs_D, r_rf_A_n1, 
             r_rf_A_n2, r_cam_A_n1, r_cam_A_n2]
    agents: [embed, BDSAgent_C1, EstStats]

    explore:
        num_episodes: 300
        num_episodes_videos: 5
        explorer: expswitch_t1
        max_episode_len: 30

    servo:
        num_episodes: 20
        num_episodes_videos: 20
        max_episode_len: 10
        displacement: 2
        
    servonav:
        num_episodes: 20
        num_episodes_videos: 20
        max_episode_len: 600
        resolution: 0.25
        fail_if_not_working: false
        

