- id: bo_app1a
  desc: 'Simple example without nuisances.'
  code:
  - bootstrapping_olympics.programs.manager.experiments_utils.experiment_explore_learn_compmake
  - robots: [r_cam_A, r_rf_A, r_fs_A]
    agents: [embed, BDSAgent_C1, EstStats]
    explore:
        num_episodes: 200
        num_episodes_videos: 5
        explorer: expswitch_t1
        max_episode_len: 30
    servo:
        num_episodes:  100
        num_episodes_videos: 5
        max_episode_len: 10
        displacement: 0.5
    servonav:
        num_episodes: 20
        num_episodes_videos: 10
        max_episode_len: 600
        resolution: 0.5

- id: bo_app1b
  desc: ""
  code:
  - bootstrapping_olympics.programs.manager.experiments_utils.experiment_explore_learn_compmake
  - robots: ['r_cam_A', 'r_rf_A', 'r_fs_A', 
            'r_rf_A_n1', 'r_rf_A_n2',
            'r_cam_A_n1', 'r_cam_A_n2']
    agents: [embed, BDSAgent_C1, EstStats]
    explore:
        num_episodes: 300
        num_episodes_videos: 5
        explorer: expswitch_t1
        max_episode_len: 30
    servo:
        num_episodes:  100
        num_episodes_videos: 10
        max_episode_len: 10
        displacement: 0.5
    servonav:
        num_episodes: 20
        num_episodes_videos: 10
        max_episode_len: 10
        resolution: 0.5

