- id: diffeo_test_light
  desc: 'Try everything fast'
  code:
  - bootstrapping_olympics.batch_jobs1
  - robots: ['r-d_SE2_dd_v2-rf360-pc', 'r-d_SE2_car_v-rf360-pc']
    agents: ['icra12-diffeo-vehicles_c']
    explore:
        num_episodes: 10
        num_episodes_videos: 1
        explorer: expswitch_t1
        max_episode_len: 10
