
# These are the normal robots

- id: r-d_SE2_car_v-rf360
  desc: ""
  code:
     - vehicles_boot.BOVehicleSimulation
     - dt: 0.05
       vehicle: d_SE2_car_v-rf360
       world: SBox2_10a

- id: r-d_SE2_dd_v2-rf360
  desc: ""
  code:
     - vehicles_boot.BOVehicleSimulation
     - dt: 0.05
       vehicle: d_SE2_dd_v2-rf360
       world: SBox2_10a

- id: r-d_SE2_dd_v-rf360
  desc: ""
  code:
     - vehicles_boot.BOVehicleSimulation
     - dt: 0.05
       vehicle: d_SE2_dd_v-rf360
       world: SBox2_10a

# These are the variations with the popcode

- id: r-d_SE2_car_v-rf360-pc
  desc: ""
  code:
  - bootstrapping_olympics.library.robots.EquivRobot
  - robot: r-d_SE2_car_v-rf360
    cmd_nuisance: []
    obs_nuisance: [n_popcode128]

- id: r-d_SE2_dd_v2-rf360-pc
  desc: ""
  code:
  - bootstrapping_olympics.library.robots.EquivRobot
  - robot: r-d_SE2_dd_v2-rf360
    cmd_nuisance: []
    obs_nuisance: [n_popcode128]

- id: r-d_SE2_dd_v-rf360-pc
  desc: ""
  code:
  - bootstrapping_olympics.library.robots.EquivRobot
  - robot: r-d_SE2_dd_v-rf360
    cmd_nuisance: []
    obs_nuisance: [n_popcode128]
