- id: "rsim-${vehicle}"
  desc: ""
  code:
     - vehicles_boot.BOVehicleSimulation
     - dt: 0.033
       id_vehicle: "${vehicle}"
       id_world: SBox2_10a # Need SBox2 for sources

- id: r_fs_A
  desc: ""
  code:
     - vehicles_boot.BOVehicleSimulation
     - dt: 0.033
       id_vehicle: v_fs_A
       id_world: SBox2_10a # Need SBox2 for sources

- id: r_cam_A
  desc: ""
  code:
     - vehicles_boot.BOVehicleSimulation
     - dt: 0.033
       id_vehicle: v_cam_A
       id_world: SBox2_10a

- id: r_fs_B
  desc: "Field sampler with square disposition"
  code:
     - vehicles_boot.BOVehicleSimulation
     - dt: 0.033
       id_vehicle: v_fs_B
       id_world: SBox2_10a # Need SBox2 for sources


- id: r_fs_C
  desc: "Field sampler with square disposition"
  code:
    - vehicles_boot.BOVehicleSimulation
    - dt: 0.033
      id_vehicle: v_fs_C
      id_world: SBox2_10a # Need SBox2 for sources

- id: r_fs_D
  desc: "Field sampler with square disposition"
  code:
      - vehicles_boot.BOVehicleSimulation
      - dt: 0.033
        id_vehicle: v_fs_D
        id_world: SBox2_10a # Need SBox2 for sources

- id: r_cam_A_n1
  desc: "Camera with permutation perturbation."
  code:
     - bootstrapping_olympics.library.robots.EquivRobot
     - robot: r_cam_A
       obs_nuisance: n_rpermA
       cmd_nuisance: []

- id: r_cam_A_n2
  desc: "Camera with scaling perturbation."
  code:
     - bootstrapping_olympics.library.robots.EquivRobot
     - robot: r_cam_A
       obs_nuisance: n_rscaleA
       cmd_nuisance: []

- id: r_rf_A
  desc: ""
  code:
     - vehicles_boot.BOVehicleSimulation
     - dt: 0.033
       id_vehicle: v_rf_A
       id_world: SBox2_10a

- id: r_rf_A_n1
  desc: "Range-finder with permutation perturbation."
  code:
    - bootstrapping_olympics.library.robots.EquivRobot
    - robot: r_rf_A
      obs_nuisance: n_rpermA
      cmd_nuisance: []

- id: r_rf_A_n2
  desc: "Range-finder with scaling perturbation."
  code:
     - bootstrapping_olympics.library.robots.EquivRobot
     - robot: r_rf_A
       obs_nuisance: n_rscaleA
       cmd_nuisance: []


