# This file contains experimental logs

- id: unicornA_base1_2013-04-02-20-37-43
  desc: "37m, nominal, boxes"
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": ~/01-youbot-ros-logs-good/unicornA_base1_2013-04-02-20-37-43.bag
        "file:outside": ~/01-youbot-ros-logs-good/unicornA_base1_2013-04-02-20-37-43.outside.mp4
      annotations:
        robot: &unicornA_base1
          name: unicorn
          shape: unicornA
          profile: base1
        motion:
          agent: babbler  
        environment: &lab_boxes3
          name: vehicles_lab
          config: boxes3
        events:
          disturbances: []
        notes: |
          video: 2013-04-02 21_44_16 (id).mov 11.3 GB 37 min
          babbler: --frequency=1 --min_length=3 --max_length=10 --levy=1 
          status: Finished “active” after crash but ok
        use_for_learning: true

  
- id: unicornA_base1_2013-04-03-12-58-11
  desc: "17m, nominal, boxes"
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": ~/01-youbot-ros-logs-good/unicornA_base1_2013-04-03-12-58-11.bag
        "file:outside": ~/01-youbot-ros-logs-good/unicornA_base1_2013-04-03-12-58-11.outside.mp4
      annotations:
        robot: *unicornA_base1
        environment: *lab_boxes3
        events:
          disturbances: []
        use_for_learning: true
        notes: |
          2013-04-03 14_04_46 (id).mov 17 min
          babbler:--frequency=1 --min_length=10 --max_length=30 --levy=1
          status: short, not sure why it stopped

- id: unicornA_base1_2013-04-03-13-16-53
  desc: "7m, Crashes into curtains after 7 minutes; don't use for learning."
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": ~/01-youbot-ros-logs-good/unicornA_base1_2013-04-03-13-16-53.bag
        "file:outside": ~/01-youbot-ros-logs-good/unicornA_base1_2013-04-03-13-16-53.outside.mp4
      annotations:
        robot: *unicornA_base1
        environment: *lab_boxes3
        events:
          disturbances: []
        use_for_learning: False
        disturbance: 
        - type: crash
          time: 000 # XXX  
        notes: |
          2013-04-03 14_23_23 (id).mov  7 min
          babbler: --frequency=1 --min_length=10 --max_length=30 --levy=1
          crashes into curtains

- id: unicornA_base1_2013-04-03-13-30-28
  desc: "38m, nominal, ok"
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": ~/01-youbot-ros-logs-good/unicornA_base1_2013-04-03-13-30-28.bag
        "file:outside": ~/01-youbot-ros-logs-good/unicornA_base1_2013-04-03-13-30-28.outside.mp4
      annotations:
        robot: *unicornA_base1
        environment: *lab_boxes3
        events:
          disturbances: []
        use_for_learning: true
        disturbance: []
        notes: |
          2013-04-03 14_37_13 (id).mov   38 min
          Changed: warn_distance=0.65 (from 0.55); ignore_closer=0.35 (from 0.4)
          babbler: --frequency=1 --min_length=10 --max_length=30 --levy=1

- id: unicornA_base1_2013-04-03-16-36-03
  desc: "17m, nominal, ends for under-voltage"
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": ~/01-youbot-ros-logs-good/unicornA_base1_2013-04-03-16-36-03.bag
        "file:outside": ~/01-youbot-ros-logs-good/unicornA_base1_2013-04-03-16-36-03.outside.mp4
      annotations:
        robot: *unicornA_base1
        environment: *lab_boxes3
        events:
          disturbances: []
        use_for_learning: true
        disturbance: []
        notes: |
          2013-04-03 17_43_05 (id).mov   16:53
          canon camera  starts a bit late (1 second or so)
          status: ends for under voltag

- id: unicornA_base1_2013-04-06-15-30-06
  desc: "6m, nominal"
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": ~/01-youbot-ros-logs-good/unicornA_base1_2013-04-06-15-30-06.bag
        "file:outside": ~/01-youbot-ros-logs-good/unicornA_base1_2013-04-06-15-30-06.outside.mp4
      annotations:
        robot: *unicornA_base1
        environment: *lab_boxes3
        events:
          disturbances: []
        use_for_learning: true
        disturbance: []
        notes: |
          original video: 2013-04-06 14_31_36 (id).mov
    
- id: unicornA_base1_2013-04-06-19-44-59
  desc: "people standing around; don't use for learning"
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": ~/01-youbot-ros-logs-good/unicornA_base1_2013-04-06-19-44-59.bag
      annotations:
        robot: *unicornA_base1
        environment: *lab_boxes3
        events:
          disturbances: ['people'] 
        use_for_learning: true
        notes: |
          no video available -- camera battery died
    

- id:  unicornA_base1_2013-04-08-19-10-12
  desc: "15m, has occlusions for camera"
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": ~/01-youbot-ros-logs-good/unicornA_base1_2013-04-08-19-10-12.bag
      annotations:
        robot: *unicornA_base1
        motion:
          agent: babbler  
        environment: &lab_empty
          name: vehicles_lab
          config: empty
        events:
          disturbances: [fixture_occlusion]
        notes: |
          starts at power 82, ended at 67
          added 1 m safe distance
          has wireless adapter in the frame of the front camera
          doesn't have external video


- id:  unicornA_base1_2013-04-08-16-43-10
  desc: "25m, gripper not properly placed"
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": ~/01-youbot-ros-logs-good/unicornA_base1_2013-04-08-16-43-10.bag
      annotations:
        robot: *unicornA_base1
        motion:
          agent: babbler  
        environment: *lab_empty
        events:
          disturbances: [wrong_arm_position]
        notes: | 
          doesn't have external video
          new hardware: wireless adapter
          cables are partially covering the hokuyos
          ends with robot falling outside of arena at 17:14 
          also not sure if the gripper was properly placed;
          this could be a good test case for the variation of the model

- id: unicornA_tran1_2013-04-09-14-35-11
  desc: "??min, nominal"
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": ~/01-youbot-ros-logs-good/unicornA_tran1_2013-04-09-14-35-11.bag
        "file:outside": ~/01-youbot-ros-logs-good/unicornA_tran1_2013-04-09-14-35-11.outside.mp4
      annotations:
        robot: &unicornA_tran1
          name: unicorn
          shape: unicornA
          profile: tran1
        motion:
          agent: babbler  
        environment: *lab_empty
        events:
          disturbances: []
        notes: |
          This is the first with translation only.
          We have video of the first part; stops after 24 minutes
          Original video: 2013-04-09 13_36_28 (id).mov 
          Started battery at 90, stopped when low

- id: unicornA_car1_2013-04-08-21-37-47
  desc: "??m, nominal"
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": ~/01-youbot-ros-logs-good/unicornA_car1_2013-04-08-21-37-47.bag
        "file:outside": ~/01-youbot-ros-logs-good/unicornA_car1_2013-04-08-21-37-47.outside.mp4
      annotations:
        robot: &unicornA_car1
          name: unicorn
          shape: unicornA
          profile: car1
        motion:
          agent: babbler  
        environment: *lab_empty
        events:
          disturbances: []
        notes: |
          This is the first one with the car-like
          We have the camera outside, but after 23 minutes it says "camera overheating".



# - id:  unicornA_tran1_2013-04-09-18-03-16.bag
#   desc: 
#   code:
#     - rosstream2boot.ExpLogFromYaml
#     - files:
#         "file:bag": ~/01-youbot-ros-logs-good/unicornA_tran1_2013-04-09-18-03-16.bag
#       annotations:
#         robot: *unicornA_tran1
#         motion:
#           agent: babbler  
#         environment: *lab_empty
#         events:
#           disturbances: []
#         notes: | 
#           starts at 82 battery, ends 22
#           no video: forgot to press play on camera
#
#

           
- id: unicornA_base1_2013-04-11-20-14-27
  desc: ""
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": ~/01-youbot-ros-logs-good/unicornA_base1_2013-04-11-20-14-27.bag
        "file:outside": ~/01-youbot-ros-logs-good/unicornA_base1_2013-04-11-20-14-27.outside.mp4
      annotations:
        robot: *unicornA_base1
        motion:
          agent: babbler  
        environment: &lab_emptyw
          name: vehicles_lab
          config: emptyw
        events:
          disturbances: []
        notes: | 
          Now I finally realized that black does not reflect the Hokuyo.
          I turned the barriers around, white instead of random patterns.
          Ends after 30 min, ok.
        

- id: unicornA_tran1_2013-04-11-23-21-36 
  desc: This is a manually controlled run in a small corner of the lab using translation. 
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": ~/01-youbot-ros-logs-good/unicornA_tran1_2013-04-11-23-21-36.bag
      annotations:
        robot: *unicornA_base1
        motion:
          agent: manual
        environment: &lab_corner
          name: lab_corner
          config: default
        events:
          disturbances: []
        notes: | 
          no video
          moved using only translations



- id: unicornA_tran1_2013-04-12-22-29-16
  desc: translation only in a lab corner
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": ~/01-youbot-ros-logs-good/unicornA_tran1_2013-04-12-22-29-16.bag
        "file:outside": ~/01-youbot-ros-logs-good/unicornA_tran1_2013-04-12-22-29-16.outside.mp4
      annotations:
        robot: *unicornA_tran1
        motion:
          agent: babbler  
        environment: *lab_corner
        events:
          disturbances: []
        notes: | 
          babbler has shorter intervals than usual: L in (5??? --10???)
          original video: 2013-04-12 21_30_34 (id).mov

- id: unicornA_tran1_2013-04-12-22-40-02
  desc: same, with 4/4
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": ~/01-youbot-ros-logs-good/unicornA_tran1_2013-04-12-22-40-02.bag
      annotations:
        robot: *unicornA_tran1
        motion:
          agent: babbler  
        environment: *lab_corner
        events:
          disturbances: []
        notes: | 
          babbler has interval [4,4]
          camera didn't save

- id:  unicornA_tran1_2013-04-12-23-34-08
  desc: manually driven along grid
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": ~/01-youbot-ros-logs-good/unicornA_tran1_2013-04-12-23-34-08.bag
        "file:outside": ~/01-youbot-ros-logs-good/unicornA_tran1_2013-04-12-23-34-08.outside.mp4
      annotations:
        robot: *unicornA_tran1
        motion:
          agent: babbler  
        environment: *lab_corner
        events:
          disturbances: []
        notes: | 
          Manually driven in a grid
          Note that at the end  I rotate a bit by mistake

- id: unicornA_servocorner_2013-04-16-22-46-46
  desc: Experiments with rotation
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": ~/01-youbot-ros-logs-good/unicornA_servocorner_2013-04-16-22-46-46.bag
        "file:outside": ~/01-youbot-ros-logs-good/unicornA_servocorner_2013-04-16-22-46-46.outside.mp4
      annotations:
        robot: *unicornA_base1
        motion:
          agent: servo  
        environment: *lab_corner
        events:
          disturbances: [andrea_panels]
        notes: | 
          - The rosbag didn't work well and messages were dropped
          - also note that this does not have the "servo_state" message.
          
          video 2013-04-16 21_47_35 (id).mov
          Log with experiments 
          
          exp10
              <param name='config_dir' 
                   value='/data/work/scm/boot12env/src/bvapps/1304-youbot/'/> 
          <param name='id_agent' value='exp10_bdser1'/>
          <param name='id_robot' value='uA_b1_tw_hlhr_s4'/>
          <param name='id_ros_robot_adapter' value='unicornA_base1_tw_hlhr_sane_s4'/>
          
          <param name='error_threshold' value='0.01'/>
          
          <param name='K' value='[1,1,0.5]'/>


# unicornA_servocorner_laseronly_2013-04-17-18-05-07.bag  exp08 but forgot camera



- id: unicornA_servocorner_laseronly_2013-04-17-18-14-07
  desc:  "Servo experiments with translation"
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": ~/01-youbot-ros-logs-good/unicornA_servocorner_laseronly_2013-04-17-18-14-07.groovy.bag
        "file:outside": ~/01-youbot-ros-logs-good/unicornA_servocorner_laseronly_2013-04-17-18-14-07.outside.mp4
      annotations:
        robot: *unicornA_tran1
        motion:
          agent: servo  
        environment: *lab_corner
        events:
          disturbances: [andrea_panels]
        notes: | 
          - no cameras in log
          - original video: 2013-04-17 17:16:06
          - The robot would disalign so I had to put it back 

          - The bag file is somehow corrupted; I can read y, y_goal, state
            but not u

# unicornA_servocorner_laseronly_2013-04-17-23-30-55.bag  servo xyth  camera did not record




- id: unicornA_servocorner_laseronly_2013-04-18-15-33-19
  desc:  "Servo experiments with also rotation"
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": ~/01-youbot-ros-logs-good/unicornA_servocorner_laseronly_2013-04-18-15-33-19.bag
        "file:outside": ~/01-youbot-ros-logs-good/unicornA_servocorner_laseronly_2013-04-18-15-33-19.outside.mp4
      annotations:
        robot: *unicornA_base1
        motion:
          agent: servo  
        environment: *lab_corner
        events:
          disturbances: [andrea_panels]
        notes: | 
          xxx
          
# /ros-logs/.


- id: unicornA_servocorner_laseronly_2013-04-23-21-40-22
  desc:  "Servo experiments with camera, only translation"
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": ~/01-youbot-ros-logs-good/unicornA_servocorner_laseronly_2013-04-23-21-40-22.bag
        "file:outside": ~/01-youbot-ros-logs-good/unicornA_servocorner_laseronly_2013-04-23-21-40-22.outside.mp4
      annotations:
        robot: *unicornA_base1
        motion:
          agent: servo  
        environment: *lab_corner
        events:
          disturbances: [andrea_panels, light]
        notes: | 
          "laseronly" in the name is wrong
 
##########################################
# Template:
# - id:  
#   desc: 
#   code:
#     - rosstream2boot.ExpLogFromYaml
#     - files:
#         "file:bag": ~/01-youbot-ros-logs-good/.bag
#         "file:outside": ~/01-youbot-ros-logs-good/.mp4
#       annotations:
#         robot: *unicornA_conf
#         motion:
#           agent: babbler  
#         environment: *env
#         events:
#           disturbances: []
#         notes: | 
##########################################


