
- id: "rsim-${vehicle}"
  desc: ""
  code:
     - vehicles_boot.BOVehicleSimulation
     - dt: 0.033
       vehicle: "${vehicle}"
       world: SBox2_10a # XXX to change 


- id: "rsimfixed-${vehicle}"
  desc: "TODO: make something move"
  code:
    - vehicles_boot.BOVehicleSimulation
    - dt: 0.033
      vehicle: "${vehicle}"
      world: SBox2_10a #XXX empty_fixed_obstacles


- id: "rsimf-${vehicle}"
  desc: "Simulation in a simple world"
  code:
  - vehicles_boot.BOVehicleSimulation
  - dt: 0.033
    vehicle: "${vehicle}"
    world: simple-world-column


- id: "rsimw-${vehicle}"
  desc: "Robot in front of a wall"
  code:
  - vehicles_boot.BOVehicleSimulation
  - dt: 0.033
    vehicle: "${vehicle}"
    world: simple-wall
    safety_margin: 1
