
- id: bv-anims-2a
  desc: 'car like and differential drive'
  code:
  - bootstrapping_olympics.batch_jobs1
  - robots: [
      "rsim-d_SE2_car_v-cam360",
      "rsim-d_SE2_car_v-rf360",
      "rsim-d_SE2_car_v-cam180", 
      "rsim-d_SE2_car_v-rf180", 
      "rsim-d_SE2_car_v-fs_05_rand144", 
      "rsim-d_SE2_car_v-fs_05_12x12", 
      "rsim-d_SE2_dd_v-cam360",
      "rsim-d_SE2_dd_v-rf360",
      "rsim-d_SE2_dd_v-cam180", 
      "rsim-d_SE2_dd_v-rf180", 
      "rsim-d_SE2_dd_v-fs_05_rand144", 
      "rsim-d_SE2_dd_v-fs_05_12x12", 
      "rsim-landroid-4cam",
      "rsim-landroid-hokuyo",
      "rsim-landroid-hokuyo-4cam"
    ]
    agents: [expswitch_t1]
    explore:
        num_episodes: 1
        num_episodes_videos: 1
        explorer: fixed_1s
        max_episode_len: 5
        videos: [close_data_no, close_nodata_no, close_nodata_sbu,
        close_onlydata_no]


- id: bv-anims-2c
  desc: 'omnidirectional (different agent)'
  code:
  - bootstrapping_olympics.batch_jobs1
  - robots: [
      "rsim-d_SE2_rb_v-cam180",
      "rsim-d_SE2_rb_v-cam360",
      "rsim-d_SE2_rb_v-cam180-stereo",
      "rsim-d_SE2_rb_v-fs_05_rand144", 
      "rsim-d_SE2_rb_v-fs_05_12x12", 
      "rsim-d_SE2_rb_v-rf180",
      "rsim-d_SE2_rb_v-rf360",
    ]
    agents: [expswitch_t1]
    explore:
        num_episodes: 1
        num_episodes_videos: 1
        explorer: fixed_10s
        max_episode_len: 5
        videos: [close_data_no, close_nodata_no, close_nodata_sbu,
                close_onlydata_no]


- id: bv-anims-2b
  desc: 'Fixed sensors (to display sensels)'
  code:
  - bootstrapping_olympics.batch_jobs1
  - robots: [
      "rsimfixed-d_fixed-cam360",
      "rsimfixed-d_fixed-rf360",
      "rsimfixed-d_fixed-cam180",
      "rsimfixed-d_fixed-rf180",
      "rsimfixed-d_fixed-fs_05_12x12",
      "rsimfixed-d_fixed-fs_05_rand144",
    ]
    agents: [expswitch_t1]
    explore:
        num_episodes: 1
        num_episodes_videos: 1
        explorer: fixed_1s
        max_episode_len: 10
        videos: [close_data_no, close_data_sb,
        close_onlydata_no] 
        # Not working yet
        #, close_data_no_z1_tran]


- id: bv-anims-2d
  desc: 'Orbs (S1 dynamics)'
  code:
  - bootstrapping_olympics.batch_jobs1
  - robots: [
      "rsim-d_S1_rb_v-cam180",
      "rsim-d_S1_rb_v-rf180",
    ]
    agents: [expswitch_t1]
    explore:
        num_episodes: 1
        num_episodes_videos: 1
        explorer: expswitch_t1
        max_episode_len: 20
        videos: [close_data_no_z1, close_data_no, close_data_sb, close_nodata_sbu,
        close_onlydata_no]


- id: bv-anims-2e
  desc: 'Simple animations of forward motion for camera and range-finder.'
  code:
  - bootstrapping_olympics.batch_jobs1
  - robots: [
      "rsimf-d_SE2_dd_v-cam180",
      "rsimf-d_SE2_dd_v-rf180",
      "rsimf-d_SE2_dd_v-cam360",
      "rsimf-d_SE2_dd_v-rf360",
    ]
    agents: [expswitch_t1]
    explore:
        num_episodes: 2
        num_episodes_videos: 2
        explorer: fixed_01
        max_episode_len: 3
        videos: ["for-bv-anims-2e", "mp4sensels_plot", "mp4z0sb"]



- id: bv-anims-2f
  desc: 'Camera in front of a wall'
  code:
  - bootstrapping_olympics.batch_jobs1
  - robots: [
            "rsimw-d_S1_rb_v-cam180"
    ]
    agents: [expswitch_t1]
    explore:
        num_episodes: 1
        num_episodes_videos: 1
        explorer: expswitch_t1
        max_episode_len: 3
        videos: [mp4z0no, "for-bv-anims-2f"]




        

