- id: stats1
  desc: Computes simple statistics (1D data)
  code:
  - boot_agents.EstStats
  - beta: 1 # XXX

- id: stats2
  desc: Computes simple statistics (2D data)
  code:
  - boot_agents.EstStats2D
  - beta: 1 # XXX

- id: bdse1
  desc: "BDSE agent"
  code:
      - boot_agents.BDSEAgent
      - change_fraction: 0.5
        explorer: expsw1
        rcond: 0.000000001
        servo:
          strategy: S1n
          gain: 0.1

# The simple explorer used in most cases
- id: expsw1
  desc: Switches randomly between commands with an exponential switching time.
  code:
      - boot_agents.ExpSwitcher
      - beta: 1


- id: exp04_bdse1
  desc: "BDSE agent"
  code:
      - boot_agents.BDSEAgent
      - change_fraction: 0.5
        explorer: expsw1
        rcond: 0.0001
        servo:
          linpoint: goal
          strategy: S1n
          gain: 0.1

# BGDS and variations

- id: exp06_bgds1
  desc: "BGDS agent"
  code:
      - boot_agents.BGDSAgent
      - beta: 1


- id: exp07_bgdsr1
  desc: "BGDS agent robust"
  code:
      - boot_agents.BGDSAgent1DRobust
      - explorer: expsw1
        importance:
        - boot_agents.Importance
        - max_y_dot: 0.1
          max_gy: 0.1
          min_y: 0
          max_y: 1


- id: exp08_bdser1
  desc: "BDSE agent robust"
  code:
      - boot_agents.BDSEAgentRobust
      - explorer: expsw1
        rcond: 0.0001
        importance:
        - boot_agents.Importance
        - max_y_dot: 0.1
          max_gy: 0.1
          min_y: 0
          max_y: 1


- id: "exp09_bdser_${num}"
  desc: "BDSE agent robust"
  code:
  - boot_agents.BDSEAgentRobust
  - explorer: expsw1
    rcond: 0.0001
    importance: &importance
    - boot_agents.Importance
    - max_y_dot: 0.1
      max_gy: 0.1
      min_y: 0
      max_y: 1

- id: exp10_bdser1
  desc: "BDSE agent robust"
  code:
  - boot_agents.BDSEAgentRobust
  - explorer: expsw1
    rcond: 0.0001
    importance: *importance

- id: exp13_bdser1
  desc: "BDSE agent robust"
  code:
  - boot_agents.BDSEAgentRobust
  - explorer: expsw1
    rcond: 0.0001
    importance: *importance



- id: exp14_bdser_s1
  desc: "BDSE agent robust, servo original"
  code:
  - boot_agents.BDSEAgentRobust
  - explorer: expsw1
    rcond: 0.0001
    importance: *importance
    servo:
    - boot_agents.BDSEServo 
    - strategy: S1
      gain: 0.1
      linpoint: current

- id: exp14_bdser_s2
  desc: "BDSE agent robust, servo simple"
  code:
  - boot_agents.BDSEAgentRobust
  - explorer: expsw1
    rcond: 0.0001
    importance: *importance
    servo:
    - boot_agents.BDSEServoSimple
    - gain: 0.1

- id: exp14_bdser_s3
  desc: "BDSE agent robust, servo long term"
  code:
  - boot_agents.BDSEAgentRobust
  - explorer: expsw1
    rcond: 0.0001
    importance: *importance
    servo:
    - boot_agents.BDSEServoLongTerm
    - grid:
        mode: uniform
        grid_max: 10.0
        grid_n: 20




