
- id: unicornA_cr_320
  desc: "Adapter for eye right camera, 320x240 grayscale"
  code:
  - rosstream2boot.library.CameraAdapterGray
  - topic: '/cam_eye_right/image_raw/compressed'
    shape: [240, 320]

- id: unicornA_cf_320
  desc: "Adapter for front camera, 320x240 grayscale"
  code:
  - rosstream2boot.library.CameraAdapterGray
  - topic: '/cam_back/image_raw/compressed'
    shape: [240, 320]

- id: unicornA_cf_320_1D
  desc: 'Vertical average of camera data'
  code:
  - rosstream2boot.library.ROSObservationsAdapterNuisance.from_yaml
  - id_adapter: unicornA_cf_320
    id_nuisance: camh1d

- id: unicornA_cf_320_1D_strip
  desc: 'Vertical average of camera data, on a strip of 1/3 of the image.'
  code:
  - rosstream2boot.library.ROSObservationsAdapterNuisance.from_yaml
  - id_adapter: unicornA_cf_320
    id_nuisance: camh1d_third


- id: unicornA_hl
  desc: Hokuyo left (?)
  code:
  - rosstream2boot.library.LaserScanAdapter
  - topic: '/scan_hokuyo_H1204906'
    index_from: 0
    index_to: 768
    min_range: 0.02
    max_range: 5.5

- id: unicornA_hr
  desc: Hokuyo right (?)
  code:
  - rosstream2boot.library.LaserScanAdapter
  - topic: '/scan_hokuyo_H1205005'
    index_from: 0
    index_to: 768
    min_range: 0.02
    max_range: 5.5

- id: unicornA_hlhr
  desc: Both Hokuyos 
  code:
  - rosstream2boot.library.SensorJoin.from_yaml
  - obs_adapters:
    - unicornA_hl
    - unicornA_hr

- id: unicornA_hlhr_sane_s4
  desc: 'Both Hokuyos, sanitized, undersampled 4x'
  code:
  - rosstream2boot.library.ROSObservationsAdapterNuisance.from_yaml
  - id_adapter: unicornA_hlhr
    id_nuisance: unicornA_hlhr_sane_s4


# scan1='/scan_hokuyo_H1204906'
# scan2='/scan_hokuyo_H1205005'
# cam1='/cam_eye_right/image_raw/compressed'
# cam2='/cam_back/image_raw/compressed'
