# hr: hokuyo right
# hl: hokuyo left
# cf: camera front (actually cam_back in the ROS conf)
# cr: camera right eye

# - id: unicornA_base1_hl
# - id: unicornA_base1_hr
# - id: unicornA_base1_hlhr
# scan1='/scan_hokuyo_H1204906'
# scan2='/scan_hokuyo_H1205005'
# cam1='/cam_eye_right/image_raw/compressed'
# cam2='/cam_back/image_raw/compressed'

- id: unicornA_base1_tw_cf
  desc: Only front camera
  code:
  - rosstream2boot.ROSRobotAdapter.from_yaml
  - obs_adapter: unicornA_cf_320
    cmd_adapter: twist_1_1
    sync:
      policy: obs-first-topic

- id: unicornA_base1_tw_hr
  desc: Only right (?) hokuyo
  code:
  - rosstream2boot.ROSRobotAdapter.from_yaml
  - obs_adapter: unicornA_hr
    cmd_adapter: twist_1_1
    sync:
      policy: obs-first-topic

- id: unicornA_base1_tw_hl
  desc: Only left (?) hokuyo
  code:
  - rosstream2boot.ROSRobotAdapter.from_yaml
  - obs_adapter: unicornA_hl
    cmd_adapter: twist_1_1
    sync:
      policy: obs-first-topic

- id: unicornA_base1_tw_hlhr
  desc: Only left (?) hokuyo
  code:
  - rosstream2boot.ROSRobotAdapter.from_yaml
  - obs_adapter: unicornA_hlhr
    cmd_adapter: twist_1_1
    sync:
      policy: obs-first-topic

- id: unicornA_base1_tw_hlhr_sane
  desc: Only left (?) hokuyo
  code:
  - rosstream2boot.ROSRobotAdapter.from_yaml
  - obs_adapter: unicornA_hlhr_sane
    cmd_adapter: twist_1_1
    sync:
      policy: obs-first-topic

- id: unicornA_base1_tw_hlhr_sane_s4
  desc: Only left (?) hokuyo
  code:
  - rosstream2boot.ROSRobotAdapter.from_yaml
  - obs_adapter: unicornA_hlhr_sane_s4
    cmd_adapter: twist_1_1
    sync:
      policy: obs-first-topic

- id: exp05_uA_xy
  desc: "Two Hokuyos, xy translation"
  code:
  - rosstream2boot.ROSRobotAdapter.from_yaml
  - obs_adapter: unicornA_hlhr_sane_s4
    cmd_adapter: twist_xy_1
    sync:
      policy: obs-first-topic


- id: uA_b1_tw_cf
  desc: "Grayscale 1D frontal camera, base1"
  code:
  - rosstream2boot.ROSRobotAdapter.from_yaml
  - obs_adapter: unicornA_cf_320_1D
    cmd_adapter: twist_1_1
    sync:
      policy: obs-first-topic


- id: uA_b1_tw_cf_strip
  desc: "Grayscale 1D frontal camera, base1"
  code:
  - rosstream2boot.ROSRobotAdapter.from_yaml
  - obs_adapter: unicornA_cf_320_1D_strip
    cmd_adapter: twist_1_1
    sync:
      policy: obs-first-topic

- id: uA_b1_xy_cf_strip
  desc: "Grayscale 1D frontal camera, only translation"
  code:
  - rosstream2boot.ROSRobotAdapter.from_yaml
  - obs_adapter: unicornA_cf_320_1D_strip
    cmd_adapter: twist_xy_1
    sync:
      policy: obs-first-topic



# - id: unicornA_base1_crcf
# - id: unicornA_base1_crcfhrhl