- id: rb1
  desc: 'Planar robot on SE2'
  code: 
  - vehicles.library.dynamics.SE2Dynamics
  - max_linear_velocity: [1,1]
    max_angular_velocity: 1
    #noise_drift: [0.05, 0.05, 0.05]

- id: rb2
  desc: 'Planar robot on SE2 (twice as fast)'
  code: 
  - vehicles.library.dynamics.SE2Dynamics
  - max_linear_velocity: [2,2]
    max_angular_velocity: 2
    #noise_drift: [0.05, 0.05, 0.05]

- id: d1rb1
  desc: 'Robot with some dynamics'
  code: 
  - vehicles.library.dynamics.SE2Force
  - max_force: [1,1,1]
    mass: 1
    damping: 1

- id: d2rb1
  desc: 'Robot with some dynamics'
  code: 
  - vehicles.library.dynamics.SE2Force
  - max_force: [1,1,1]
    mass: 2
    damping: 1
    