- id: "rb1${sensor}"
  desc: ""
  id_dynamics: rb1
  sensors:
    - id_sensor: "${sensor}"
  radius: 0.5
  extra:
    skin: omni

- id: "cl1${sensor}"
  desc: ""
  id_dynamics: cl1
  sensors:
    - id_sensor: "${sensor}"
  radius: 0.5
  extra:
    skin: car_with_wheels


- id: "dd1${sensor}"
  desc: ""
  id_dynamics: dd1
  sensors:
    - id_sensor: "${sensor}"
  radius: 0.5
  extra:
    skin: ddrive


- id: "rb2${sensor}"
  desc: ""
  id_dynamics: rb2
  sensors:
    - id_sensor: "${sensor}"
  radius: 0.5
  extra:
    skin: omni

- id: "rb1Mr1${sensor}"
  desc: ""
  id_dynamics: rb1
  sensors:
    - id_sensor: "${sensor}"
      pose: [0,0,45]
  radius: 0.5
  extra:
    skin: omni
  
- id: "rb1Mx1${sensor}"
  desc: ""
  id_dynamics: rb1
  sensors:
    - id_sensor: "${sensor}"
      pose: [0.1,0,0]
  radius: 0.5
  extra:
    skin: omni

- id: "rb1My1${sensor}"
  desc: ""
  id_dynamics: rb1
  sensors:
    - id_sensor: "${sensor}"
      pose: [0,0.1,0]
  radius: 0.5
  extra:
    skin: omni

- id: "d1rb1${sensor}"
  desc: ""
  id_dynamics: d1rb1
  sensors:
    - id_sensor: "${sensor}"
  radius: 0.5
  extra:
    skin: omni

- id: "d2rb1${sensor}"
  desc: ""
  id_dynamics: d2rb1
  sensors:
    - id_sensor: "${sensor}"
  radius: 0.5
  extra:
    skin: omni

- id: "rb1Proco"
  desc: "Vehicle with both sensors"
  id_dynamics: d2rb1
  sensors:
    - id_sensor: ro
    - id_sensor: co
  radius: 0.5
  extra:
    skin: omni






# # Three configurations

# - id: "v_c${conf}_${sensor}"
#   desc: "Vehicle with the sensor ${sensor} mounted at conf ${conf}."
#   id_dynamics: SE2_rb_v
#   sensors:
#     - id_sensor: "${sensor}"
#       pose: "${conf|A=[0,0,0];B=[0.25,0,0];C=[0.25,0,0]}"
#   radius: 0.5
#   extra:
#     skin: omni

 
