# - id: bdse1a
#   desc: ''
#   code:
#   - bootstrapping_olympics.batch_jobs1
#   - robots: [
#         r_vrounA_wA,
#         r_vcounA_wA,
#         r_vrounA_wB,
#         r_vcounA_wB]
#     agents: [BDSEAgent_C1, BDSEAgent_C2]
#     explore:
#         num_episodes: 200
#         num_episodes_videos: 5
#         explorer: expSwitch_t1
#         max_episode_len: 30
#         videos: [exz1sb, exz1no]
#     servo:
#         num_episodes: 20
#         num_episodes_videos: 5
#         max_episode_len: 60
#         displacement: 1
#     servonav:
#         num_episodes: 10
#         num_episodes_videos: 10
#         max_episode_len: 600
#         resolution: 0.25
#         fail_if_not_working: false


- id: bv_bds_comp_quick
  desc: 'Quick check'
  code:
  - bootstrapping_olympics.batch_jobs1
  - robots: [
        # Base cases
        Se0Vrb1ro,
        Se0Vrb1co,
        Se0Vrb1ifsc1,
        # Comparison for noise level
        Ygn1Se0Vrb1ro,
        Ygn2Se0Vrb1ro,
        Ygn1Se0Vrb1co,
        Ygn2Se0Vrb1co,
        # Different environment
        Se1Vrb1ro,
        Se1Vrb1co, 
        # Different pose
        Se0Vrb1Mr1ro,
        Se0Vrb1Mx1ro,
        Se0Vrb1My1ro,
        # Sensels/commands permutations
        Yrp1Se0Vrb1ro,
        Urp1Se0Vrb1ro,
        # Field of view
        Se0Vrb1rc,
        Se0Vrb1rh,
        Se0Vrb1rq,
        # Random linear transform
        Yrl1Se0Vrb1ro,
        Yrl2Se0Vrb1ro,
        # Nonlinear transformations
        Ynl1Se0Vrb1ro,
        Ynl2Se0Vrb1ro,
        # Second-order dynamics
        Se0Vd1rb1ro,
        Se0Vd2rb1ro,
        # Faster dynamics
        Se0Vrb2ro,
        # Two sensors in parallel
        Se0Vrb1Proco,
        # Noise on the dynamics
        Ugn1Se0Vrb1co,
        Ugn2Se0Vrb1co
]
    agents: [BDSEAgent_C1] #, BDSEAgent_C2]
    explore:
        num_episodes: 1
        num_episodes_videos: 1
        explorer: expswitch_t1
        max_episode_len: 30
        videos: [exz1sb, exz1no] 
