- id: fsq1
  desc: "Uniform disposition"
  code: 
    - vehicles.library.sensors.FieldSamplerUniform
    - sides: [0.22,0.22]
      shape: [12,12]
      normalize: False

- id: fsq2
  desc: "Uniform disposition (128x128)"
  code: 
    - vehicles.library.sensors.FieldSamplerUniform
    - sides: [0.22,0.22]
      shape: [128,128]
      normalize: False


- id: fo1
  desc: "Circular disposition"
  code: 
    - vehicles.library.sensors.FieldSamplerCircle
    - radius: 0.2
      n: 144
      fov_deg: 360
      normalize: False


- id: ifsc1
  desc: "Random circular distribution"
  code: 
    - vehicles.library.sensors.FieldSamplerRandCircle
    - radius: 0.38   # So it can fit inside radius 0.5
      n: 144
      normalize: False
                
- id: s4co
  desc: "An omnidirectional camera with 180 sensels, sigma = 4 deg"
  code: 
      - vehicles.library.sensors.PhotoreceptorsSmoothUniform
      - num_sensels: 180
        fov_deg:     360
        spatial_sigma_deg: 4
        upsample: 15

- id: s8cc
  desc: "An omnidirectional camera with 180 sensels, sigma = 8 deg"
  code: 
      - vehicles.library.sensors.PhotoreceptorsSmoothUniform
      - num_sensels: 180
        fov_deg:     180
        spatial_sigma_deg: 8
        upsample: 15

- id: co
  desc: "An omnidirectional camera with 180 sensels"
  code: 
      - vehicles.library.sensors.PhotoreceptorsSmoothUniform
      - num_sensels: 180
        fov_deg:     360
        spatial_sigma_deg: 0.01
        upsample: 1

- id: s1co2
  desc: "128 sensels, 2 deg smooth"
  code: 
      - vehicles.library.sensors.PhotoreceptorsSmoothUniform
      - num_sensels: 128
        fov_deg:     360
        spatial_sigma_deg: 0.01
        upsample: 2

- id: ico
  desc: "An omnidirectional camera with 180 sensels, irregularly sampled"
  code: 
      - vehicles.library.sensors.PhotoreceptorsSmoothRandom
      - num_sensels: 180
        fov_deg:     360
        spatial_sigma_deg: 0
            
- id: s4cc
  desc: "An omnidirectional camera with 180 sensels, sigma = 4 deg"
  code: 
      - vehicles.library.sensors.PhotoreceptorsSmoothUniform
      - num_sensels: 180
        fov_deg:     180
        spatial_sigma_deg: 4
        upsample: 15

         
- id: s2cc
  desc: "An omnidirectional camera with 180 sensels, sigma = 4 deg"
  code: 
      - vehicles.library.sensors.PhotoreceptorsSmoothUniform
      - num_sensels: 180
        fov_deg:     180
        spatial_sigma_deg: 2
        upsample: 15

- id: s1cc
  desc: "An omnidirectional camera with 180 sensels, sigma = 4 deg"
  code: 
      - vehicles.library.sensors.PhotoreceptorsSmoothUniform
      - num_sensels: 180
        fov_deg:     180
        spatial_sigma_deg: 1
        upsample: 15

- id: s1co
  desc: "An omnidirectional camera with 180 sensels, sigma = 4 deg"
  code: 
      - vehicles.library.sensors.PhotoreceptorsSmoothUniform
      - num_sensels: 180
        fov_deg:     360
        spatial_sigma_deg: 1
        upsample: 15

- id: s1cic
  desc: "An omnidirectional camera with 180 sensels, sigma = 4 deg"
  code: 
      - vehicles.library.sensors.PhotoreceptorsSmoothRandom
      - num_sensels: 180
        fov_deg:     180
        spatial_sigma_deg: 1
        upsample: 15


- id: is4cc
  desc: |
    An omnidirectional camera with 180 sensels, sigma = 4 deg, 
    irregular sampling.
  code: 
      - vehicles.library.sensors.PhotoreceptorsSmoothRandom
      - num_sensels: 180
        fov_deg:     180
        spatial_sigma_deg: 4
        upsample: 15

- id: cc
  desc: "An omnidirectional camera with 180 sensels"
  code: 
      - vehicles.library.sensors.PhotoreceptorsSmoothUniform
      - num_sensels: 180
        fov_deg:     180
        spatial_sigma_deg: 0.01 # XXX: should be 0
        upsample: 1

# FIXME: change to ro1
- id: ro
  desc:  ""
  code: 
    - "vehicles.library.sensors.RangefinderUniform"
    - num_sensels: 360
      fov_deg:     360

- id: ro2
  desc:  "Range finder with 128 rays"
  code: 
    - "vehicles.library.sensors.RangefinderUniform"
    - num_sensels: 128
      fov_deg:     360


- id: n16ro
  desc:  ""
  code: 
    - "vehicles.library.sensors.RangefinderUniform"
    - num_sensels: 16
      fov_deg:     360

- id: rc
  desc:  ""
  code: 
    - "vehicles.library.sensors.RangefinderUniform"
    - num_sensels: 180
      fov_deg:     180

- id: rh
  desc:  ""
  code: 
    - "vehicles.library.sensors.RangefinderUniform"
    - num_sensels: 180
      fov_deg:     90
 
- id: rq
  desc:  ""
  code: 
    - "vehicles.library.sensors.RangefinderUniform"
    - num_sensels: 180
      fov_deg:     45


