- id: fsq1
  desc: "Uniform disposition"
  code: 
    - vehicles.library.sensors.FieldSamplerUniform
    - sides: [0.22,0.22]
      shape: [12,12]
      normalize: False

- id: fo1
  desc: "Circular disposition"
  code: 
    - vehicles.library.sensors.FieldSamplerCircle
    - radius: 0.2
      n: 144
      fov_deg: 360
      normalize: False


- id: ifsc1
  desc: "Random circular distribution"
  code: 
    - vehicles.library.sensors.FieldSamplerRandCircle
    - radius: 0.38   # So it can fit inside radius 0.5
      n: 144
      normalize: False
                
- id: s4co
  desc: "An omnidirectional camera with 180 sensels, sigma = 4 deg"
  code: 
      - vehicles.library.sensors.PhotoreceptorsSmoothUniform
      - num_sensels: 180
        fov_deg:     360
        spatial_sigma_deg: 4
        upsample: 15

- id: s8cc
  desc: "An omnidirectional camera with 180 sensels, sigma = 8 deg"
  code: 
      - vehicles.library.sensors.PhotoreceptorsSmoothUniform
      - num_sensels: 180
        fov_deg:     180
        spatial_sigma_deg: 8
        upsample: 15

- id: co
  desc: "An omnidirectional camera with 180 sensels"
  code: 
      - vehicles.library.sensors.PhotoreceptorsSmoothUniform
      - num_sensels: 180
        fov_deg:     360
        spatial_sigma_deg: 0.01
        upsample: 1

- id: ico
  desc: "An omnidirectional camera with 180 sensels, irregularly sampled"
  code: 
      - vehicles.library.sensors.PhotoreceptorsSmoothRandom
      - num_sensels: 180
        fov_deg:     360
        spatial_sigma_deg: 0
            
- id: s4cc
  desc: "An omnidirectional camera with 180 sensels, sigma = 4 deg"
  code: 
      - vehicles.library.sensors.PhotoreceptorsSmoothUniform
      - num_sensels: 180
        fov_deg:     180
        spatial_sigma_deg: 4
        upsample: 15

         
- id: s2cc
  desc: "An omnidirectional camera with 180 sensels, sigma = 4 deg"
  code: 
      - vehicles.library.sensors.PhotoreceptorsSmoothUniform
      - num_sensels: 180
        fov_deg:     180
        spatial_sigma_deg: 2
        upsample: 15

- id: s1cc
  desc: "An omnidirectional camera with 180 sensels, sigma = 4 deg"
  code: 
      - vehicles.library.sensors.PhotoreceptorsSmoothUniform
      - num_sensels: 180
        fov_deg:     180
        spatial_sigma_deg: 1
        upsample: 15

- id: s1co
  desc: "An omnidirectional camera with 180 sensels, sigma = 4 deg"
  code: 
      - vehicles.library.sensors.PhotoreceptorsSmoothUniform
      - num_sensels: 180
        fov_deg:     360
        spatial_sigma_deg: 1
        upsample: 15

- id: s1cic
  desc: "An omnidirectional camera with 180 sensels, sigma = 4 deg"
  code: 
      - vehicles.library.sensors.PhotoreceptorsSmoothRandom
      - num_sensels: 180
        fov_deg:     180
        spatial_sigma_deg: 1
        upsample: 15


- id: is4cc
  desc: |
    An omnidirectional camera with 180 sensels, sigma = 4 deg, 
    irregular sampling.
  code: 
      - vehicles.library.sensors.PhotoreceptorsSmoothRandom
      - num_sensels: 180
        fov_deg:     180
        spatial_sigma_deg: 4
        upsample: 15

- id: cc
  desc: "An omnidirectional camera with 180 sensels"
  code: 
      - vehicles.library.sensors.PhotoreceptorsSmoothUniform
      - num_sensels: 180
        fov_deg:     180
        spatial_sigma_deg: 0.01 # XXX: should be 0
        upsample: 1

- id: ro
  desc:  ""
  code: 
    - "vehicles.library.sensors.RangefinderUniform"
    - num_sensels: 360
      fov_deg:     360

- id: n16ro
  desc:  ""
  code: 
    - "vehicles.library.sensors.RangefinderUniform"
    - num_sensels: 16
      fov_deg:     360

- id: rc
  desc:  ""
  code: 
    - "vehicles.library.sensors.RangefinderUniform"
    - num_sensels: 180
      fov_deg:     180

- id: rh
  desc:  ""
  code: 
    - "vehicles.library.sensors.RangefinderUniform"
    - num_sensels: 180
      fov_deg:     90
 
- id: rq
  desc:  ""
  code: 
    - "vehicles.library.sensors.RangefinderUniform"
    - num_sensels: 180
      fov_deg:     45


# - id: "n0${sensor}"
#   desc: ""
#   code: 
#       - vehicles.library.sensors.Filter
#       - id_sensor: "${sensor}"
#         code: 
#           - vehicles.library.noises.AdditiveGaussian
#           - std_dev: 0

# - id: "n1${sensor}"
#   desc: ""
#   code: 
#       - vehicles.library.sensors.Filter
#       - id_sensor: "${sensor}"
#         code: 
#           - vehicles.library.noises.AdditiveGaussian
#           - std_dev: 0.01

# - id: "n2${sensor}"
#   desc: ""
#   code: 
#       - vehicles.library.sensors.Filter
#       - id_sensor: "${sensor}"
#         code: 
#           - vehicles.library.noises.AdditiveGaussian
#           - std_dev: 0.05


- id: "cam_f${fov}n${n}d${disp}s${smoothdeg}_n${noiselevel}"
  desc: ""
  code: 
      - "vehicles.library.sensors.PhotoreceptorsSmooth${disp|U=Uniform;R=Random}"
      - num_sensels: "${n}"
        fov_deg:     "${fov}"
        spatial_sigma_deg: "${smoothdeg}"
        upsample: 15
        noise: 
            - vehicles.library.noises.AdditiveGaussian
            - std_dev: "${noiselevel|0=0;1=0.01;2=0.05}"


- id: "rf_f${fov}n${n}d${disp}_n${noiselevel}"
  desc: |
    Range-finder with ${n} rays with ${fov}deg field of view,
    noise level ${noiselevel} (${noiselevel|0=0;1=0.1;2=0.5}},
    and ${disp|U=uniform;R=random} disposition.
  code: 
      - "vehicles.library.sensors.Rangefinder${disp|U=Uniform;R=Random}"
      - num_sensels: "${n}"
        fov_deg:     "${fov}"
        noise: 
            - vehicles.library.noises.AdditiveGaussian
            - std_dev: "${noiselevel|0=0;1=0.1;2=0.5}"


- id: rf_f180n180dU_n0
- id: rf_f180n180dU_n1
- id: rf_f180n180dU_n2
- id: rf_f360n180dU_n0
- id: rf_f360n180dU_n1
- id: rf_f360n180dU_n2
- id: rf_f360n180dR_n0
- id: rf_f360n180dR_n1
- id: rf_f360n180dR_n2

- id: cam_f180n180dUs4_n0
- id: cam_f180n180dUs4_n1
- id: cam_f180n180dUs4_n2
- id: cam_f360n180dUs4_n0
- id: cam_f360n180dUs4_n1
- id: cam_f360n180dUs4_n2
- id: cam_f360n180dRs4_n0
- id: cam_f360n180dRs4_n1
- id: cam_f360n180dRs4_n2
