# The simple explorer used in most cases
- id: expsw1
  desc: Switches randomly between commands with an exponential switching time.
  code:
      - boot_agents.ExpSwitcher
      - beta: 1

# XXX: to change
- id: expswitch_t1
  desc: Switches randomly between commands with an exponential switching time.
  code:
      - boot_agents.ExpSwitcher
      - beta: 1

