- id: trace
  desc: ''
  code:
  - boot_log2movie_cairo_avi
  - 'plotter.display_sidebar': False
    'plotter.width': 256
    'plotter.height': 256
    'plotter.plotting_params':
        zoom: 0
        

- id: tracesb
  desc: ''
  code:  
  - boot_log2movie_cairo_avi
  - 'plotter.display_sidebar': True
    'plotter.width': 256
    'plotter.height': 256
    'plotter.sidebar_width': 200
    'plotter.plotting_params':
        zoom: 0
    'plotter.sidebar_params':
        show_observations: False
    
        