- id: anims2c
  desc: ''
  code:
  - bootstrapping_olympics.batch_jobs1
  - robots: ['r-d_SE2_dd_v2-cam360', 'rn-d_SE2_dd_v2-cam360','r-d_SE2_car_v-cam360']
    agents: [expswitch_t1]
    explore:
        num_episodes: 9
        num_episodes_videos: 9
        explorer: canonical
        max_episode_len: 7
        videos: [trace, tracesb]

- id: anims3c
  desc: ''
  code:
  - bootstrapping_olympics.batch_jobs1
  - robots: ['r-d_SE2_rb_v-cam360']
    agents: [expswitch_t1]
    explore:
        num_episodes: 27
        num_episodes_videos: 27
        explorer: canonical
        max_episode_len: 5
        videos: [trace, tracesb]

