
- id: expswitch_t1
  desc: Switches randomly between commands with an exponential switching time.
  code:
      - boot_agents.ExpSwitcher
      - beta: 1

- id: canonical
  desc: basic motions
  code:
      - boot_agents.CanonicalCommandsAgent
      - {}
      
      

# 
# - id: motions_2
#   desc: basic motions
#   code:
#       - boot_agents.Motions
#       - actions:
#         - commands: [1, 0]
#           delta: 1
#         - commands: [1, 1]
#           delta: 1
#         - commands: [0, 1]
#           delta: 1
#         - commands: [1, 1]
#           delta: 1
#         speedup: 1
#         loop: true

