
- id: "r-${vehicle}"
  desc: ""
  code:
     - vehicles_boot.BOVehicleSimulation
     - dt: 0.033
       id_vehicle: ${vehicle}
       id_world: empty_fixed_5


- id: "rn-${vehicle}"
  desc: ""
  code:
    - bootstrapping_olympics.library.robots.EquivRobot
    - robot: "r-${vehicle}"
      cmd_nuisance: [n_GLa]
      obs_nuisance: []
          
          
