- id: bv_anims_1_brai_blind
  desc: ''
  code:
  - bootstrapping_olympics.batch_jobs1
  - robots: [r_brai_blind]
    agents: [expswitch_t1]
    explore:
        num_episodes: 8
        num_episodes_videos: 8
        explorer: canonical
        max_episode_len:5
        videos: [trace, tracesb, pdfz0sb]


- id: bv_anims_1_cars
  desc: ''
  code:
  - bootstrapping_olympics.batch_jobs1
  - robots: ["d_SE2_car_v_w-cam360-empty"]
    agents: [expswitch_t1]
    explore:
        num_episodes: 8
        num_episodes_videos: 8
        explorer: canonical
        max_episode_len: 5
        videos: [pdfz0sb]


