
- id: "rsim-${vehicle}"
  desc: ""
  code:
     - vehicles_boot.BOVehicleSimulation
     - dt: 0.033
       id_vehicle: "${vehicle}"
       id_world: rep1a_world

- id: "${robot}-afew"
  desc: "Extracts a few sensels"
  code:
    - bootstrapping_olympics.examples.EquivRobot
    - robot: "${robot}"
      cmd_nuisance: []
      obs_nuisance: [n_afew]

- id: "${robot}-bits"
  desc: "Converts to bits"
  code:
  - bootstrapping_olympics.examples.EquivRobot
  - robot: "${robot}"
    cmd_nuisance: []
    obs_nuisance: [n_int2bits]
          
- id: "${robot}-d32"
  desc: "Discretizes to 32 levels"
  code:
  - bootstrapping_olympics.examples.EquivRobot
  - robot: "${robot}"
    cmd_nuisance: []
    obs_nuisance: [n_discretize_32]
          
          
- id: "${robot}-shuffle"
  desc: "Shuffles the sensels"
  code:
  - bootstrapping_olympics.examples.EquivRobot
  - robot: "${robot}"
    cmd_nuisance: []
    obs_nuisance: [n_rpermA]
          
          
- id: "${robot}-flatten"
  desc: "Flattens to 1D array"
  code:
  - bootstrapping_olympics.examples.EquivRobot
  - robot: "${robot}"
    cmd_nuisance: []
    obs_nuisance: [n_flatten]
          
          
          

    