
- id: "${vehicle}-rsim"
  desc: ""
  code:
     - vehicles_boot.BOVehicleSimulation
     - dt: 0.033
       id_vehicle: "${vehicle}"
       # id_world: rep1a_world
       id_world: BigMama_r10s1_orig
       

- id: "${vehicle}-rsim2"
  desc: ""
  code:
    - vehicles_boot.BOVehicleSimulation
    - dt: 0.033
      id_vehicle: "${vehicle}"
      id_world: SBox2_10a       

       
- id: "${robot}-afew"
  desc: "Extracts a few sensels"
  code:
    - bootstrapping_olympics.library.robots.EquivRobot
    - robot: "${robot}"
      cmd_nuisance: []
      obs_nuisance: [n_afew]

          
          
          

    