
- id: n_afew
  desc: Selects a few sensels
  code:
    - bootstrapping_olympics.library.Select
    - which: [0, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88,
            96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176]
    
