
- id: "${vehicle}-rsim"
  desc: ""
  code:
     - vehicles_boot.BOVehicleSimulation
     - dt: 0.033
       id_vehicle: "${vehicle}"
       # id_world: rep1a_world
       id_world: BigMama_r10s1_orig
       

- id: "${vehicle}-rsim2"
  desc: ""
  code:
    - vehicles_boot.BOVehicleSimulation
    - dt: 0.033
      id_vehicle: "${vehicle}"
      id_world: SBox2_10a       

       
- id: "${robot}-afew"
  desc: "Extracts a few sensels"
  code:
    - bootstrapping_olympics.library.robots.EquivRobot
    - robot: "${robot}"
      cmd_nuisance: []
      obs_nuisance: [n_afew]

- id: "${robot}-bits"
  desc: "Converts to bits"
  code:
  - bootstrapping_olympics.library.robots.EquivRobot
  - robot: "${robot}"
    cmd_nuisance: []
    obs_nuisance: [n_int2bits]
          
- id: "${robot}-gray"
  desc: "Converts to gray code"
  code:
  - bootstrapping_olympics.library.robots.EquivRobot
  - robot: "${robot}"
    cmd_nuisance: []
    obs_nuisance: [n_int2gray]
          

- id: "${robot}-d32"
  desc: "Discretizes to 32 levels"
  code:
  - bootstrapping_olympics.library.robots.EquivRobot
  - robot: "${robot}"
    cmd_nuisance: []
    obs_nuisance: [n_discretize_32]
          
          
- id: "${robot}-shuffle"
  desc: "Shuffles the sensels"
  code:
  - bootstrapping_olympics.library.robots.EquivRobot
  - robot: "${robot}"
    cmd_nuisance: []
    obs_nuisance: [n_rpermA]
          
          
- id: "${robot}-flatten"
  desc: "Flattens to 1D array"
  code:
  - bootstrapping_olympics.library.robots.EquivRobot
  - robot: "${robot}"
    cmd_nuisance: []
    obs_nuisance: [n_flatten]
    
      
          
          
- id: "${robot}-crypt"
  desc: "Encrypts the bits."
  code:
  - bootstrapping_olympics.library.robots.EquivRobot
  - robot: "${robot}"
    cmd_nuisance: []
    obs_nuisance: [n_encrypt1]
          
          
          
          

    