
# BDS and variations

- id: bdse1
  desc: "BDSE agent "
  code:
  - boot_agents_bdse.BDSEAgent2
  - estimator: 
    - bdse.BDSEEstimator
    - rcond: 0.000000001
    servo:
    - boot_agents_bdse.BDSEServo
    - gain: 0.1
      linpoint: current

- id: bdse3
  desc: "BDSE agent (linpoint=curr) "
  code:
  - boot_agents_bdse.BDSEAgent2
  - estimator: 
    - bdse.BDSEEstimator
    - rcond: 0.000000001
    servo:
    - boot_agents_bdse.BDSEServo
    - gain: 0.05
      linpoint: current

# - id: bdse1_smid
#   desc: "BDSE agent "
#   code:
#       - boot_agents_bdse.BDSEAgent2
#       - rcond: 0.000000001
#         servo:
#           gain: 0.05
#           linpoint: middle

- id: bdse4
  desc: "BDSE agent (linpoint=goal)"
  code:
  - boot_agents_bdse.BDSEAgent2
  - estimator: 
    - bdse.BDSEEstimator
    - rcond: 0.000000001
    servo:
    - boot_agents_bdse.BDSEServo
    - gain: 0.05
      linpoint: goal


- id: bdse2
  desc: "BDSE agent (higher rcond)"
  code:
  - boot_agents_bdse.BDSEAgent2
  - estimator: 
    - bdse.BDSEEstimator
    - rcond: 0.001

