- id: "rsim-${vehicle}"
  desc: ""
  code:
     - vehicles_boot.BOVehicleSimulation
     - dt: 0.033
       vehicle: "${vehicle}"
       world: SBox2_10a # Need SBox2 for sources


- id: r_turret
  desc: Robot with turret
  code:
     - vehicles_boot.BOVehicleSimulation
     - dt: 0.033
       vehicle: turret
       world: stochastic_box_10


- id: r_turret_rf
  desc: Robot with turret
  code:
     - vehicles_boot.BOVehicleSimulation
     - dt: 0.033
       vehicle: turret_rf
       world: stochastic_box_10