- id: "rsim-${vehicle}"
  desc: ""
  code:
     - vehicles_boot.BOVehicleSimulation
     - dt: 0.033
       id_vehicle: "${vehicle}"
       id_world: SBox2_10a # Need SBox2 for sources


- id: r_turret
  desc: Robot with turret
  code:
     - vehicles_boot.BOVehicleSimulation
     - dt: 0.033
       id_vehicle: turret
       id_world: stochastic_box_10


- id: r_turret_rf
  desc: Robot with turret
  code:
     - vehicles_boot.BOVehicleSimulation
     - dt: 0.033
       id_vehicle: turret_rf
       id_world: stochastic_box_10