
- id: "rsim-${vehicle}"
  desc: ""
  code:
    - vehicles_boot.BOVehicleSimulation
    - dt: 0.033
      vehicle: "${vehicle}"
      world: SBox2_10a       
      
- id: "onev-${robot}" 
  desc: "Converts bits to 1 integer value (symbols)"
  code:
    - bootstrapping_olympics.library.robots.EquivRobot
    - robot: "${robot}"
      cmd_nuisance: []
      obs_nuisance: [to2d, bits2int]

          
          

         
          
          
